[default]
REDDIT_CLIENT_ID = "krrAZLQFlgkhXPbV_O-pfw"
REDDIT_CLIENT_SECRET = "5ya8Iv9_mk2-0hXJmbOmOrbC9JENsw"

TWITTER_API_KEY = "pK2AtVRpfr7muU9AV3Fh75I6m"
TWITTER_API_SECRET = "46l1Wv3o3CpVEMsaMKnjgsQr0TxkGsWxvSYmTyZyWG8wBykOWI"
TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAG6O4gEAAAAArKbZX30rCePYGSewWnUuOBh1Io8%3DPK9QIeW6idgDTaT5GZyug0mJk0cP2FTcaMTFIMCPBTTHw7g3CE"
TWITTER_ACCESS_TOKEN = "1690346610696597505-TAvJMsV3Y4yjexpG4LzSBGeIV5qpjY"
TWITTER_ACCESS_TOKEN_SECRETE = "7ayyoqy1NQN2gEfW0lj1pT11RMy5u3pKuRUoJpk5r5zSB"
